---
# The path to a single bag to process
#bag_path: "/tmp/directory/to/single/BAG_DIRECTORY"

# The path to a directory containing multiple bags to bulk process
#bags_directory: "/tmp/directory/to/many/bags"

# Processed items metadata backup and logging base path
cache_and_logging_path: "cache/processed_items"

# Hydra server configurations for posting new works and files
hydra_endpoint:
  # Seconds to wait before timing out for a response from the server, default (60)
  server_timeout: 600
  server_domain: "http://hydra.server"

  # The CSRF token form field.
  csrf_form_field: "authenticity_token"
  login:
    # The url to the login page for the Hydra app. Some authentications systems, such as CAS, will redirect
    # from this url to the authentication hosts page. 
    #
    # Make a custom 'migration' admin user in the system for login and processing new works.
    url: "/users/sign_in?locale=en"
    username: "admin_user@hydra.server"
    password: "abc123"
    authentication_token: "abc123"

    # If the url is redirected to another authentication system, such as CAS, the configurations set below should be
    # relative to the form that is presented to the user for typing in their username and password.

    # The login form's ID, will default to using the first form on the page if this ID is not set.
    form_id: "new_user"
    # The name of the username/login field on the form.
    username_form_field: "user[email]"
    # The name of the password field on the form.
    password_form_field: "user[password]"

  # Configuration for a "generic_work" on Hydra.. this configuration needs modification when operating with different
  # work types, such as "Book", "ETD", "Article", etc.
  new_work:
    # The url to the page to generate a new work
    url: "/concern/defaults/new?locale=en"
    # The form action used on the new work page for posting a new work. This is used as a selector to properly identify
    # which form on the page will be used for manipulation and submission.. as well as grabbing the CSRF token from it.
    form_action: "/concern/defaults?locale=en"

  # Similar to configurations for a new work, this form action creates a child of a specific work type.
  child_work:
    form_action: "/concern/parent/%{parent_id}/defaults?locale=en"

  # The URL for querying a list of admin sets in the system.
  admin_sets:
    url: "/admin/admin_sets?locale=en"

  # Workflow advancement url, fields, and control
  workflow_actions:
    # Should the work be advanced in its workflow after being published to the server?
    # (DEFAULT) true unless explicitly set to false here
    auto_advance_work: false
    
    # The URL format, including the work ID to "PUT" a workflow update to.
    url: "/concern/workflow_actions/%{id}?locale=en"
    
    actions:
      # Workflow action name, such as 'approve'
      - name:
          field:
            name: name
            property: "workflow_action.%{field_name}"
            type: String
          # The name of the workflow step configured and loaded into the Hyrax instance.
          value: "approve"
        # Workflow action comment field
        comment:
          field:
            name: comment
            property: "workflow_action.%{field_name}"
            type: String
          value: "Approved by data migration user."

  # Standard Hydra file upload url.
  uploads:
    url: "/uploads"
    files_form_field: "files[]"

# DSpace bag file default configurations
bag:
  manifest_file: "manifest-md5.txt"
  bagit_file: "bagit.txt"
  tagmanifest_file: "tagmanifest-md5.txt"

  # An Item is the primary thing described by the metadata and object.properties, and can contain any number of attached
  # files (ItemFile) in sub-directories along with its associated metadata.
  item:
    directory: "data/"
    metadata_file: "metadata.xml"
    object_properties_file: "object.properties"

    # An ItemFile is an attached file to the Item, these are found in sub-directories and each file has an associated
    # metadata xml file.
    item_file:
      directory_pattern: "data/.*/"
      metadata_file_name_template: "{item_file_name}-metadata.xml"
      description_xpath: "//metadata/value[@name='description']"
      name_xpath: "//metadata/value[@name='name']"
      sequence_id_xpath: "//metadata/value[@name='sequence_id']"
      source_xpath: "//metadata/value[@name='source']"
