require 'nokogiri'
require_relative '../mapping/mapping'
require_relative 'metadata/class_method_runner'
require_relative 'metadata/custom_node'
require_relative 'metadata/node'
require_relative 'metadata/qualifier'
