---
# ETD Hyrax work type
work_type: "default_work"

# Default AdminSet.id, or "" to use Hyrax "Default Admin Set"
admin_set_id: ""

upload_data:
  - directory: ORIGINAL
    ignore_files:

uploaded_files:
  field:
    name: "uploaded_files"
    property: "%{field_name}"
    type: Array

hydra_endpoint:
  server_domain: "http://localhost:3000"
  # Configuration for a "generic_work" on Hydra.. this configuration needs modification when operating with different
  # work types, such as "Book", "ETD", "Article", etc.
  new_work:
    # The url to the page to generate a new work
    url: "/concern/default_works/new?locale=en"
    # The form action used on the new work page for posting a new work. This is used as a selector to properly identify
    # which form on the page will be used for manipulation and submission.. as well as grabbing the CSRF token from it.
    form_action: "/concern/default_works?locale=en"
    # The CSRF hidden from field name to grab and use for actions such as posting file uploads. The web UI has an AJAX
    # file upload capability that makes use of this token with posting new files to the "uploads" url.
    csrf_form_field: "authenticity_token"

# Add this value to the migration data
# (DEFAULT) 'always' : always add this value to the migration data
# 'except_empty_value' : add this value except for empty/nil
# 'if_form_field_value_missing' : add the value if the form_field doesn't have an existing value
# 'never' : do not add this value to the migration data
# 'except_empty_value' : add the value unless it is empty or nil, in which case ignore it
value_add_to_migration: except_empty_value

# When operating on a node, grab the value from its property. The property would likely
# be pulling from the configuration and/or value passed to a commandline arg.
# (DEFAULT) : Don't use a node property, use the standard value from CustomNode or Qualifier behavior
# (EXAMPLE) admin_set_id : A CustomNode may get the AdminSet ID provided in configuration or overridden on the commandline
value_from_node_property: ''

# Custom metadata nodes to add to the data payload posted to the server
custom_nodes:
  admin_set:
    field:
      name: admin_set_id
      property: "%{work_type}.%{field_name}"
      type: String
    method: Mapping::AdminSet.unprocessed
    value_from_node_property: admin_set_id
  agreement:
    field:
      name: agreement
      property: "%{field_name}"
      type: Integer
    method: Mapping::Agreement.unprocessed
    value: 1
  keyword:
    field:
      name: keyword
      property: "%{work_type}.%{field_name}"
      type: Array
    method: Mapping::Keyword.unprocessed
    value: data-migration
  rights:
    field:
      name: rights
      property: "%{work_type}.%{field_name}"
      type: Array
    method: Mapping::Rights.unprocessed
    value: "http://rightsstatements.org/vocab/CNE/1.0/"
    value_add_to_migration: if_form_field_value_missing
  visibility:
    field:
      name: visibility
      property: "%{work_type}.%{field_name}"
      type: Array
    method: Mapping::Visibility.unprocessed
    value: open

# Migration metadata nodes extract data from the DSpace Item metadata.xml and do some
# lookup/cleanup/mapping before posting to the server.
migration_nodes:
  creator:
    field:
      name: creator
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='creator']"
    method: Mapping::Creator.unprocessed
    qualifiers:
      default:
        field:
          name: creator
  date:
    field:
      name: date_created
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='date']"
    method: Mapping::Date.unprocessed
    qualifiers:
      default:
        field:
          name: date_created
      accessioned:
        field:
          name: date_issued
      available:
        field:
          name: date_available
      issued:
        field:
          name: date_issued
      updated:
        field:
          name: date_updated
      copyright:
        field:
          name: date_copyright
  description:
    field:
      name: description
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='description']"
    method: Mapping::Description.unprocessed
    qualifiers:
      default:
        field:
          name: description
      abstract:
        field:
          name: description
      digitization:
        field:
          name: digitization_spec
      embargo:
        field:
          name: visibility
        method:
          # set visibility to 'embargo' and embargo_release_date to the value from the node
          - Mapping::Description.set_embargo
          - visibility
          - embargo_release_date
      embargopolicy:
        field:
          name: visibility_during_embargo
        method:
          # set embargo policy during and after embargo
          - Mapping::Description.lookup_embargo_policy
          - visibility_during_embargo
          - visibility_after_embargo
      peerreview:
        field:
          name: peerreviewed
      peerreviewnotes:
        field:
          name: additional_information
        method:
          - Mapping::Description.prepend
          - 'description.peerreviewnotes : '
      provenance:
        field:
          name: additional_information
        method:
          - Mapping::Description.prepend
          - 'description.provenance : '
      sponsorship:
        field:
          name: funding_statement
      tableofcontents:
        field:
          name: tableofcontents
  format:
    field:
      name: file_format
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='format']"
    method: Mapping::format.unprocessed
    qualifiers:
      default:
        field:
          name: file_format
      extent:
        field:
          name: file_extent
      mimetype:
        field:
          name: file_format
  identifier:
    field:
      name: identifier_uri
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='identifier']"
    method: Mapping::Identifier.unprocessed
    qualifiers:
      default:
        field:
          name: identifier_uri
      citation:
        field:
          name: bibliographic_citation
      isbn:
        field:
          name: isbn
      uri:
        field:
          name: identifier_uri
      doi:
        field:
          name: doi
  language:
    field:
      name: language
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='language']"
    method: Mapping::Language.unprocessed
    qualifiers:
      default:
        field:
          name: language
      iso:
        field:
          name: language
        method: Mapping::Language.uri
  publisher:
    field:
      name: publisher
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='publisher']"
    method: Mapping::Publisher.unprocessed
    qualifiers:
      default:
        field:
          name: publisher
  relation:
    field:
      name: relation
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='relation']"
    method: Mapping::Relation.unprocessed
    qualifiers:
      default:
        field:
          name: relation
      ispartofseries:
        field:
          name: in_series
  rights:
    field:
      name: rights
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='rights']"
    method: Mapping::Rights.unprocessed
    qualifiers:
      default:
        field:
          name: rights
        method: Mapping::Rights.ignored
      uri:
        field:
          name: rights
  subject:
    field:
      name: keyword
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='subject']"
    method: Mapping::Subject.unprocessed
    qualifiers:
      default:
        field:
          name: keyword
      lcsh:
        field:
          name: subject
        method: Mapping::Subject.uri
  title:
    field:
      name: title
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='title']"
    method: Mapping::Title.unprocessed
    qualifiers:
      default:
        field:
          name: title
      alternative:
        field:
          name: alt_title
  type:
    field:
      name: resource_type
      property: "%{work_type}.%{field_name}"
      type: Array
    xpath: "//metadata/value[@element='type']"
    method: Mapping::Type.unprocessed
    qualifiers:
      default:
        field:
          name: resource_type
